# Generated by Django 3.2.25 on 2026-01-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descripotion',
            new_name='description',
        ),
    ]
